### ISSUE TITLE
Examples of procedural rendering!

### ISSUE THREAD

**Issue by dylanbeattie** [dylanbeattie/netcentric-summit-2022#1]
![image](https://user-images.githubusercontent.com/106178/160131791-fb017d37-0056-43a3-9246-8aa8dbb52206.png)

**Comment by albertoruibal** [comment]
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1803607/160132953-77674818-e0bc-4385-9d7e-d8d4e27efdaa.png">

        let r = 255 * Math.sin(200 - x / 20  - y / 20);
        let g = 255 * Math.cos(- x / 20 );
        let b = 255 * Math.cos(- y / 20 * x /20);
        return `rgb(${r},${g},${b})`;

**Comment by dylanbeattie** [comment]
```
(x, y) => {
      let r = 255 * Math.sin(200 - x / 20) + 255 * Math.cos(150 - y / 20)
      let g = 50 * Math.sin(200 - x / 40) + (5 * Math.cos(150 - y / 10))
      let b = 255 * Math.cos(150 - y / 20)
      if (x % 20 == 0 || y % 20 == 0) g = 255;
      return `rgb(${r},${g},${b})`
  }
```
   
    
![image](https://user-images.githubusercontent.com/106178/160133246-be2ac08f-011f-4d25-a1a2-0647189dcf25.png)

**Comment by elmojito** [comment]
![image](https://user-images.githubusercontent.com/317336/160133969-84ecb2f9-5e77-4647-9e59-48ae05b2e7d5.png)

**Comment by albertoramosN** [comment]
<img width="407" alt="Screenshot 2022-03-25 at 14 55 08" src="https://user-images.githubusercontent.com/101729915/160134169-1ea4223b-ce78-4b0f-a9c5-9947d9ae6846.png">

```
  (x, y) => {
        let r = (1 * x) % 1050
        let g = (x* + y) % 3000
        let b = y % 400
        return `rgb(${r},${b},${g})`
  }
```

**Comment by elmojito** [comment]
![image](https://user-images.githubusercontent.com/317336/160134834-f1ef4c48-8135-4524-b11d-5ec18cd7b824.png)

**Comment by albertoruibal** [comment]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/1803607/160135925-2e4deebe-3de3-4634-94b1-a79a9f22a221.png">

```
        let r = 255 * Math.sin(100 - x / 10 + y / 20 -  (x + y) / 20);
        let g = 255 * Math.cos(- x / 50 + y / 40 * (x-y)) * Math.tan(x/40);
        let b = 255 * Math.sin(- x * y / 200) * Math.tan(x-y);
        return `rgb(${r},${g},${b})`;
```

**Comment by elmojito** [comment]
![image](https://user-images.githubusercontent.com/317336/160136510-d5098067-5479-43c8-8a76-b530c80e43f2.png)

**Comment by elmojito** [comment]
![image](https://user-images.githubusercontent.com/317336/160137159-4f39f3c6-4f44-4318-b913-95d01c3dd7fb.png)

sorry, I couldn't resist. but I'm already done :)
